### PR TITLE
[docs] [ci] README badges, LICENSE & added a .travis.yml

### PR DESCRIPTION
**Pull request by elithrar**
- godoc.org and Travis badges
- A .travis.yml that runs go vet, go fmt and the race detector during tests (appropriated from https://github.com/gorilla/mux/pull/134)
- Mention the license in the README explicitly
- Privatize an exported test variable - `TestRoutes` - which wasn't used outside of this package.
- Reformatted `testRoutes` to satisfy gofmt (for some reason it likes to remove the type from the slice items) - e.g.

``` diff
var testRoutes = []testPattern{
-       testPattern{methods: nil, prefix: "/"},
+       {methods: nil, prefix: "/"},
```

Note: the Travis run will fail until the vanity domain is set up, so I can understand holding off on merging this for now.

### CODE REVIEW

**Comment by zenazn** [comment]
Aww, I already did a bunch of this :/

The `gofmt` thing is because you're passing `-s` to simplify the code. The resulting code is in fact simpler, but I'm not sure who it's harming; and since `gofmt` without arguments seems to be the standard I'm inclined to leave it.

I'm going to leave this PR open to mentally track all the things you're doing in this PR that I'm not in `master` (although if you rebase and fix everything for me I'd of course be much obliged!)

**Comment by elithrar** [comment]
Forgot that the -s flag was strict like that—agree that leaving it off is the preferred approach.

I've re-pushed this with:

* Badges
* Mention of the license in the README
* gofmt on Travis builds (useful for PRs)

Website is also looking :+1:

**Comment by ottob** [comment]
Perhaps correct the GoDoc link in https://github.com/goji/goji/blame/master/README.md#L48 at the same time?

The GoDoc link on the bottom of the new website is also wrong.

And :+1: on the new website. Looking good!

**Comment by zenazn** [comment]
I think all of this is done, so I'm closing this out.

**Pull request closed without merging**
